using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

//EM PROPRIEDADES
//tb_listaVeiculos Multiline True -> PARA PERMITIR NOVAS LINHAS

namespace aula62
{
    public partial class F_Veiculos : Form
    {
        //É NECESSARIO ESTANCIAR A CLASSE DO FORMULARIO PAI EM UM ESCOPO GLOBAL A CLASSE DO FORMULARIO FILHO
        //POIS ESTACIADA COMO UM PARAMETRO DO CONSTRUTOR DA CLASSE ELA TEM SOMENTE ACESSO NO ESCOPO DO METODO
        //ENTAO PARA SER UTILIZADA PELO EVENTO DE FECHAMENTO DO FORMULARIO FILHO PASSANDO VALORES PARA O TEXTBOX LISTA DO FORMULARIO PAI
        //PRECISA SER ACESSADA FORA DO METODO CONSTRUTOR, SENDO CRIADA DO TIPO DA CLASSE DO FORMULARIO PAI
        F_Principal fp2;
         
        //CONSTRUTOR DA CLASSE F_Veiculos FOI ALTERADO PARA RECEBER COMO PARAMETRO O TEXTO DO TEXTBOX LISTA
        //AULA64 CRIANDO PARAMETRO DE ENTRADA DO TIPO DO FORMULARIO PAI
        public F_Veiculos(string v, F_Principal fp1)
        {
            InitializeComponent();

            //MESMO QUE O TEXTBOX LISTA DESTE FORMULARIO TENHA O MESMO  NOME DO TEXTBOX LISTA DO FORMULARIO ANTERIOR
            //ELES SAO ELEMENTOS DIFERENTES POIS ESTAO EM ESCOPOS DIFERENTES, POIS ESTAO EM CLASSES DIFERENTES
            //AQUI ELE ESTA RECEBENDO O VALOR DA VARIAL QUE FOI CRIADA PARA RECEBER COMO PARAMENTRO O TEXTO DO TEXTBOX LISTA DO FORMULARIO ANTERIOR
            tb_listaVeiculos.Text = v;

            //VALOR SENDO ATRIBUIDO PARA A VARIAVEL num CRIADA NO FORMULARIO PAI
            //CONFORME EVENTO CRIADO ESTE VALOR SERÁ PASSADO PARA O FORMULARIO PARA APÓS O FECHAMENTO DO FORMULARIO FILHO
            fp1.num = 10;

            //NESTE PONTO A CLASSE RECEBIDA COMO PARAMETRO DO CONSTRUTOR É ATRIBUIDA A VARIAVEL CRIADO COM O TIPO DA CLASSE DO FORMULARIO PAI
            fp2 = fp1;
        }

        //EVENTO FormClosed DAS PROPRIEDADES DO FORMULARIO
        //PARA CRIAR EVENTO QUANDO O FORMULARIO FOR FECHADO, APOS O FECHAMENTO DO FORMULARIO FILHO SERÉ EXECUTADO O BLOCO ABAIXO
        private void F_Veiculos_FormClosed(object sender, FormClosedEventArgs e)
        {
            fp2.tb_listaVeiculos.Text = tb_listaVeiculos.Text;
        }
    }
}
